apiVersion: v1
kind: PersistentVolume
metadata:
  name: netappnfs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    path: /svm0_NFS_k8s
    server: 10.182.0.83
